### PR TITLE
Support for Version 17 Added

### PR DESCRIPTION
**Pull request by prasantht96**
#5

### CODE REVIEW

**Comment by jadengis** [comment]
Hey @prasantht96, thanks for the PR! Could you change the version number to `2.1.0`? The change as is doesn't require a major version bump. Thanks! 🙏

**Comment by prasantht96** [comment]
> Hey @prasantht96, thanks for the PR! Could you change the version number to `2.1.0`? The change as is doesn't require a major version bump. Thanks! 🙏

Done. Pls Check it.

**Comment by jadengis** [comment]
Looks good. Thanks for the PR.

**Comment by prasantht96** [comment]
Can you please publish the package? Thank you.

**Pull request merged**
